# Generated by Django 3.0.3 on 2020-02-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=20)),
                ('item', models.CharField(max_length=100)),
                ('classfication', models.CharField(max_length=30)),
                ('op_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('memo', models.TextField()),
                ('username', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
    ]
