# Generated by Django 3.0.3 on 2020-02-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
