# Generated by Django 3.0.3 on 2020-02-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashs', '0002_auto_20200213_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='username',
        ),
        migrations.AlterField(
            model_name='cash',
            name='cash_type',
            field=models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cash',
            name='classfication',
            field=models.CharField(blank=True, help_text='입출금 항목', max_length=30),
        ),
        migrations.AlterField(
            model_name='cash',
            name='item',
            field=models.CharField(help_text='업체명', max_length=100),
        ),
        migrations.AlterField(
            model_name='cash',
            name='memo',
            field=models.TextField(blank=True, help_text='비고'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='op_month',
            field=models.DateField(verbose_name='AR/AP Operating Month'),
        ),
    ]
