# Generated by Django 3.0.3 on 2020-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashs', '0003_auto_20200213_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cash',
            name='cash_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cash',
            name='op_month',
            field=models.DateField(blank=True, verbose_name='AR/AP Operating Month'),
        ),
    ]
